from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from langchain_core.messages import HumanMessage
from app.agent.agent_executor import get_agent

app = FastAPI()

# --- NEW: Add CORS Middleware ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, replace "*" with your React app's URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
# --------------------------------

# Initialize the Multi-Agent Graph
agent = get_agent()

class ChatRequest(BaseModel):
    message: str

@app.post("/chat")
def chat(req: ChatRequest):
    print(f"User Message: {req.message}")
    
    # Pass the incoming text as a HumanMessage into the Graph state
    result = agent.invoke({"messages": [HumanMessage(content=req.message)]})
    
    # LangGraph returns the entire conversational state. 
    # Extract the very last message generated by the AI agent.
    final_message = result["messages"][-1].content
    
    return {"response": final_message}